### ISSUE TITLE
All game installs fail on Ubuntu 21.10

### ISSUE THREAD

**Issue by MSchabel** [diddlesnaps/gog-galaxy-wine#28]
Hey there,

I am on the most recent version of this snap, and also ran the additional commands described in the readme.

Whenever I try to install a game, it completely downloads it, says something like "finishing installation" and then fails. As the title says I am currently on Ubuntu 21.10. Could this be the reason or am I missing something?

Regards,
Martin

**Comment by reyquito** [comment]
I'm also having this problem. Can't play any of my games.

**Comment by Succubustop** [comment]
Did you try solving it by following the instructions here? [gog support](https://support.gog.com/hc/en-us/articles/360013537357-GOG-GALAXY-Installation-failed-E2-Update-failed-E2-Failed-to-finalize-the-update?product=gog)

I also manually installed the packages inside "Dependencies" folder, don't know if it was necessary, but the error was resolved.

**Comment by wkitty42** [comment]
> I am on the most recent version of this snap, and also ran the additional commands described in the readme.

do you mean this section of the readme on the front page of this repo??
```
Some games might require you to run `snap connect gog-galaxy-wine:hardware-observe`, and/or
`snap connect gog-galaxy-wine:process-control` in a terminal
```

**Comment by MSchabel** [comment]
@wkitty42 yep those are the ones I was talking about, but I think running or not running `snap connect gog-galaxy-wine:hardware-observe`/`snap connect gog-galaxy-wine:process-control` is unrelated.

@Succubustop I know that GOG-Article and tried it, but no success.
Nevertheless: can you explain to me what exactly you did to install the packages manually?

**Comment by wkitty42** [comment]
ok, i thought that was what you meant... i have not run those (yet)...

**Comment by Succubustop** [comment]
> @Succubustop I know that GOG-Article and tried it, but no success. Nevertheless: can you explain to me what exactly you did to install the packages manually?

Firstly I have to add that I had Wine, Winetricks, dotnetfx 4.8, and corefonts installed before I tried to work with snap. Don't rightly know if this mattered, kind of a linux noob here.
As I've mentioned "Dependencies-Temp" was renamed "Dependencies". 
So what I did after this, was launch the installers with Wine Installer in the .../Dependencies/__redist/ directory, except "ISI", because that just gave a setup error. Otherwise every setup did it's job.
Restarted galaxy and oddly enough the error message came up again. After a system restart however everything was fine, and the play button was active, no more error message.
But my woes didn't end there, because the auto syncing just crashes the client. Well, We're getting there.

**Comment by MSchabel** [comment]
@Succubustop Issue fixed and I guess I am at the same stage you are at right now. What I did:

- downloaded my games
- renamed `<PathToGogDirectory>/Dependencies-Temp` to `<PathToGogDirectory>/Dependencies`
- ran all the installers in the sub-directories of `<PathToGogDirectory>/Dependencies`
- restarted the computer completely (yes this is important)
- restarted GoG-Galaxy

Now most of the games are startable, but only when I deactivate syncing. Same issue you mentioned and mentioned in #29.
